In [41]:
import pandas as pd
import numpy as np

In [42]:
# Load Training Set
zombie_train = pd.read_csv('training.csv')
zombie_train.head()

   bite_size  green_blood_count  infected_family location  is_zombie
0   0.023280          39.178580             True     east      False
1   6.366788          58.343596            False    south      False
2   4.844174         103.638594            False     west       True
3   4.139467          63.209423            False     west      False
4   1.057532          52.064286            False     west      False

In [52]:
# Load Testing Set
zombie_test = pd.read_csv('testing.csv')
zombie_test.head()

   bite_size  green_blood_count  infected_family location  is_zombie
0   0.816796          30.060504            False     west      False
1   1.674969          74.038955            False     east      False
2   2.704426          44.894736            False     east      False
3   0.559173          26.421510             True    south      False
4   7.300998          32.810592             True     west      False

### Exploratory Analysis

In [44]:
zombie_train.describe()

         bite_size  green_blood_count
count  1000.000000        1000.000000
mean      2.923613          60.101453
std       2.071724          40.852410
min       0.015092           0.429289
25%       1.169882          33.121866
50%       2.582607          49.022175
75%       4.136114          75.827047
max      10.092533         237.887051

In [45]:
zombie_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   bite_size          1000 non-null   float64
 1   green_blood_count  1000 non-null   float64
 2   infected_family    1000 non-null   bool
 3   location           1000 non-null   object
 4   is_zombie          1000 non-null   bool
dtypes: bool(2), float64(2), object(1)
memory usage: 25.5+ KB

In [46]:
# Process Location Values 
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
zombie_train[['location']] = enc.fit_transform(zombie_train[['location']])

In [47]:
zombie_train.head()

   bite_size  green_blood_count  infected_family  location  is_zombie
0   0.023280          39.178580             True       0.0      False
1   6.366788          58.343596            False       2.0      False
2   4.844174         103.638594            False       3.0       True
3   4.139467          63.209423            False       3.0      False
4   1.057532          52.064286            False       3.0      False

In [48]:
#Choose Features and Targets
y = zombie_train.is_zombie
zombie_features = ['bite_size','green_blood_count','infected_family','location']
X = zombie_train[zombie_features]

In [49]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

# Define model 
zombie_model = DecisionTreeRegressor()

# Fit model with Inputs and 
zombie_model.fit(X, y)

# Split data into training and validation date, for both features and target.
# train_X, test_X, train_y, test_y = train_test_split(

DecisionTreeRegressor()

In [50]:
print("Making predictions for the following 5 victims:")
print(X.head())
print("The predictions are")
print(zombie_model.predict(X.head()))

Making predictions for the following 5 victims:
   bite_size  green_blood_count  infected_family  location
0   0.023280          39.178580             True       0.0
1   6.366788          58.343596            False       2.0
2   4.844174         103.638594            False       3.0
3   4.139467          63.209423            False       3.0
4   1.057532          52.064286            False       3.0
The predictions are
[0. 0. 1. 0. 0.]

In [51]:
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor

def get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)